/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package socialnetworkingsite;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author hello
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        passField = new javax.swing.JTextField();
        toSignup = new javax.swing.JButton();
        userField = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Social Networking - Login");
        setBackground(new java.awt.Color(153, 51, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 106, 30));

        jLabel19.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("USER LOGIN");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 270, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Username");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 106, 30));
        jPanel1.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 280, 46));

        toSignup.setBackground(new java.awt.Color(0, 102, 102));
        toSignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        toSignup.setForeground(new java.awt.Color(255, 255, 234));
        toSignup.setText("Signup");
        toSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toSignupActionPerformed(evt);
            }
        });
        jPanel1.add(toSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 100, 30));
        jPanel1.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 140, 280, 46));

        login.setBackground(new java.awt.Color(0, 102, 102));
        login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 234));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 154, 40));

        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 252, 243));
        jLabel5.setText("Don't have an account?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toSignupActionPerformed
        new Register().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_toSignupActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
                String userName = userField.getText().trim();
        String password= passField.getText().trim();
        Login(userName,password);
    }//GEN-LAST:event_loginActionPerformed

    public void Login(String phone, String pass){
    
    if (phone.equals("")) {
        JOptionPane.showMessageDialog(null, "Enter username");
        return;
    }
    
    if (pass.equals("")) {
        JOptionPane.showMessageDialog(null, "Enter password");
        return;
    }
    
    Connection conn = dbConnection.dbconnect();
    try {

        Statement stmt = conn.createStatement();
        String query = "SELECT * FROM Users WHERE UserName='" + phone + "' AND pass='" + pass + "'";
        ResultSet resultSet = stmt.executeQuery(query);
        boolean check = resultSet.next();
        if (check) {
            JOptionPane.showMessageDialog(null, "LOGIN SUCCESSFUL");
        
            String query2 = "SELECT UserId FROM Users WHERE UserName = ?";
        try (PreparedStatement pstmt2 = conn.prepareStatement(query2)) {
            pstmt2.setString(1, phone);
            ResultSet rs = pstmt2.executeQuery();
            if (rs.next()) {
                int userId = rs.getInt("UserId");
                System.out.println("UserId of the inserted user: " + userId);  
                new Dashboard(userId).setVisible(true);
                dispose();
            }
        } catch (SQLException e) {
            System.out.println("Error retrieving UserId: " + e.getMessage());
        }
      
        } else {
            JOptionPane.showMessageDialog(null, "Invalid username or password");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JTextField passField;
    private javax.swing.JButton toSignup;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
