/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package socialnetworkingsite;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author hello
 */
public class Register extends javax.swing.JFrame {
 private Connection conn;
    private Statement stmt;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        conn = dbConnection.dbconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        btnsignup = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sportsOption = new javax.swing.JCheckBox();
        musicOption = new javax.swing.JCheckBox();
        entertainmentOption = new javax.swing.JCheckBox();
        politicsOption = new javax.swing.JCheckBox();
        scienceOption = new javax.swing.JCheckBox();
        comedyOption = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        confirmPassword = new javax.swing.JTextField();
        toSignin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 252, 243));
        jLabel4.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New User Registration");

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 252, 243));
        jLabel2.setText("Interests:");

        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnsignup.setBackground(new java.awt.Color(0, 0, 0));
        btnsignup.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btnsignup.setForeground(new java.awt.Color(255, 255, 255));
        btnsignup.setText("Sign Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });

        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 252, 243));
        jLabel5.setText("Password");

        sportsOption.setForeground(new java.awt.Color(255, 255, 255));
        sportsOption.setText("Sports");
        sportsOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsOptionActionPerformed(evt);
            }
        });

        musicOption.setForeground(new java.awt.Color(255, 255, 255));
        musicOption.setText("Music");

        entertainmentOption.setForeground(new java.awt.Color(255, 255, 255));
        entertainmentOption.setText("Entertainment");

        politicsOption.setForeground(new java.awt.Color(255, 255, 255));
        politicsOption.setText("Politics");

        scienceOption.setForeground(new java.awt.Color(255, 255, 255));
        scienceOption.setText("Science");

        comedyOption.setForeground(new java.awt.Color(255, 255, 255));
        comedyOption.setText("Comedy");

        jLabel6.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 252, 243));
        jLabel6.setText("Already have an account?");

        confirmPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        toSignin.setBackground(new java.awt.Color(0, 0, 102));
        toSignin.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        toSignin.setForeground(new java.awt.Color(255, 255, 255));
        toSignin.setText("Login");
        toSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toSigninActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 252, 243));
        jLabel7.setText("Confirm Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(musicOption, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sportsOption, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(politicsOption, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comedyOption, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entertainmentOption, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scienceOption, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(44, 44, 44)
                                .addComponent(username))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(confirmPassword))))
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toSignin)
                        .addContainerGap(236, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(btnsignup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(549, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(214, 214, 214)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(468, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sportsOption)
                    .addComponent(entertainmentOption))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musicOption)
                    .addComponent(scienceOption))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(politicsOption)
                    .addComponent(comedyOption))
                .addGap(41, 41, 41)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toSignin)
                    .addComponent(jLabel6))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(316, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(232, 232, 232)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(368, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(180, 180, 180)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed

        String Username = username.getText().trim();
        String pass = password.getText().trim();
        String Conpass = confirmPassword.getText().trim();
        List <String> selectedCat=getSelectedCategoriesFromUI();

        registerUser(Username,pass,Conpass,selectedCat);
        
    }//GEN-LAST:event_btnsignupActionPerformed

    private void sportsOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sportsOptionActionPerformed

    private void toSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toSigninActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_toSigninActionPerformed
private List<String> getSelectedCategoriesFromUI() {
    List<String> selectedCategories = new ArrayList<>();

    if (sportsOption.isSelected()) {
        selectedCategories.add("Sports");
    }
    if (entertainmentOption.isSelected()) {
        selectedCategories.add("Entertainment");
    }
    if (musicOption.isSelected()) {
        selectedCategories.add("Music");
    }
    if (politicsOption.isSelected()) {
        selectedCategories.add("Politics");
    }
    if (scienceOption.isSelected()) {
        selectedCategories.add("Science");
    }
    if (comedyOption.isSelected()) {
        selectedCategories.add("Comedy");
    }

    return selectedCategories;
}
    private void registerUser(String Username, String Password, String ConPassword, List<String> selectedCategories){
       if (Username.equals("") || Password.equals("") || ConPassword.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in all the fields");
            return;
        }
        if (!Password.equals(ConPassword)) {
            JOptionPane.showMessageDialog(null, "Passwords doesn't match");
            return;
        }
        
       try {
            Connection conn = dbConnection.dbconnect();
            String query = "SELECT UserName FROM Users WHERE UserName = ?";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, Username);
            ResultSet resultSet = statement.executeQuery();
            if (resultSet.next()) {
                JOptionPane.showMessageDialog(null, "Username Already Taken. Please choose a different one.");
                return;
            }
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error connecting to the database");
            e.printStackTrace();
            return;
        }
       String sql = "INSERT INTO Users (UserName,pass) VALUES (?, ?)";

        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
//           Assert.assertEquals("Ram", fname);
            
            pstmt.setString(1, Username);
            pstmt.setString(2, Password);

            int rowsAffected = pstmt.executeUpdate();
            if (rowsAffected > 0) {
                System.out.println("Data inserted successfully");
                JOptionPane.showMessageDialog(null, "Successfully inserted", "EMPLOYEE",
                        JOptionPane.INFORMATION_MESSAGE);
                new Login().setVisible(true);
                dispose();
                
        String query = "SELECT UserId FROM Users WHERE UserName = ?";
        try (PreparedStatement pstmt2 = conn.prepareStatement(query)) {
            pstmt2.setString(1, Username);
            ResultSet rs = pstmt2.executeQuery();
            if (rs.next()) {
                int userId = rs.getInt("UserId");
                System.out.println("UserId of the inserted user: " + userId);  
                
                String insertCategorySQL = "INSERT INTO UserCategories (UserId, CategoryId) VALUES (?, ?)";
                    try (PreparedStatement pstmtCategories = conn.prepareStatement(insertCategorySQL)) {
                        for (String category : selectedCategories) {
                            // Retrieve the CategoryId for each selected category
                            String categoryIdQuery = "SELECT CategoryId FROM Categories WHERE CategoryName = ?";
                            PreparedStatement pstmtCategoryId = conn.prepareStatement(categoryIdQuery);
                            pstmtCategoryId.setString(1, category);
                            ResultSet rsCategoryId = pstmtCategoryId.executeQuery();
                            if (rsCategoryId.next()) {
                                int categoryId = rsCategoryId.getInt("CategoryId");
                                // Insert the UserId and CategoryId into UserCategories table
                                pstmtCategories.setInt(1, userId);
                                pstmtCategories.setInt(2, categoryId);
                                pstmtCategories.addBatch();
                            }
                        }
                        // Execute batch insert
                        pstmtCategories.executeBatch();
                    }
            }
        } catch (SQLException e) {
            System.out.println("Error retrieving UserId: " + e.getMessage());
        }
            } else {
                System.out.println("Data insertion failed");
            }
        } catch (SQLException e) {
            System.out.println("Error inserting data: " + e.getMessage());
        }
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsignup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox comedyOption;
    private javax.swing.JTextField confirmPassword;
    private javax.swing.JCheckBox entertainmentOption;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox musicOption;
    private javax.swing.JTextField password;
    private javax.swing.JCheckBox politicsOption;
    private javax.swing.JCheckBox scienceOption;
    private javax.swing.JCheckBox sportsOption;
    private javax.swing.JButton toSignin;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
